name: reviewdog
on:
  pull_request:
    branches: ['main']
jobs:
  biome:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1